FROM nginx:alpine

# Copy the static assets built locally
COPY composeApp/build/dist/js/productionExecutable /usr/share/nginx/html

# Copy Nginx Template (Enable Environment Variable Substitution)
COPY nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
