FROM nginx:alpine

# Copy the static assets (Development Build - More Stable)
COPY composeApp/build/dist/js/developmentExecutable /usr/share/nginx/html

# Copy Nginx Template (Enable Environment Variable Substitution)
COPY nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
